# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='localImage',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
