# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import iss.models


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0002_image_localimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='localImage',
            field=models.FileField(blank=True, null=True, upload_to=iss.models.user_directory_path),
        ),
    ]
